In [2]:
import numpy as np

In [ ]:
numpy_array = np.array([1, 2, 3, 4, 5])
print(numpy_array)

[1 2 3 4 5]


In [4]:
# Two dimensional Numpy array
monthly_temps = np.array([[20, 25, 18], [22, 27, 19], [23, 17, 21]])
print(monthly_temps)

[[20 25 18]
 [22 27 19]
 [23 17 21]]


In [5]:
multi_list = [[1, 2, 3], [4, 5, 6]]

# Convert the list to a 2D NumPy array
multi_array = np.array(multi_list)

# Print the array
print("Multidimensional Array:\n", multi_array)

Multidimensional Array:
 [[1 2 3]
 [4 5 6]]


summing up two numpy lists

In [6]:
list_1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

list_2 = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]

sum_array = np.array(list_1)+np.array(list_2)

 Create a 1-dimensional NumPy array that starts at 10 and goes up to (but does not include) 50, with each value increasing by 2.

In [7]:
array_1d=np.arange(10,50,2)

Create an array containing 11 elements that are evenly spaced between 0 and 10 (inclusive).

In [8]:
evenly_spaced_array= np.linspace(0,10,11)
evenly_spaced_array

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

slicing and indexing

In [9]:
myArray = np.array([15, 22, 30, 38, 45])
# Slicing the array
print("First three elements:", myArray[:3]) 
print("Elements from index 2 to 4:", myArray[2:5])  
print("Every second element:", myArray[::2]) 

First three elements: [15 22 30]
Elements from index 2 to 4: [30 38 45]
Every second element: [15 30 45]


Boolean Indexing

In [10]:
temperatures = np.array([18.5, 24.2, 15.7, 21.9, 27.1, 12.3])

# Find days with temperatures below 18 degrees Celsius (inclusive)
cool_days = temperatures[temperatures <= 18]
print("Cool days (18°C or below):", cool_days)

Cool days (18°C or below): [15.7 12.3]


Fancy Indexing

In [11]:
array = np.array([1, 2, 3, 4, 5])
# Fancy indexing
indices = np.array([0, 2, 4])
print("Elements at specified indices:", array[indices])

Elements at specified indices: [1 3 5]


Use fancy indexing to select elements located at positions (0, 0), (1, 2), (2, 3), and (3, 1) from the array.¶

In [12]:
array = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12],
                     [13, 14, 15, 16]])

selected_elements=array[[0,1,2,3],[0,2,3,1]]
selected_elements

array([ 1,  7, 12, 14])

Reshaping and Resizing the Arrays

In [14]:

array = np.array([[1, 2, 3],
                  [4, 5, 6]])

# Reshape the array to have 3 rows and 2 columns
reshaped_array = array.reshape(3, 2)

print("Original array:\n", array)
print("Reshaped array:\n", reshaped_array)

Original array:
 [[1 2 3]
 [4 5 6]]
Reshaped array:
 [[1 2]
 [3 4]
 [5 6]]


In [15]:
# Example
array = np.array([1, 2, 3, 4, 5])

# Resize the array to have 8 elements
resized_array = np.resize(array, (8,))

print("Original array:", array)
print("Resized array:", resized_array)

Original array: [1 2 3 4 5]
Resized array: [1 2 3 4 5 1 2 3]


Ravel and Flatten

In [16]:
# Example
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])

# Using ravel
raveled_array = np.ravel(array_2d)

# Using flatten
flattened_array = array_2d.flatten()

print("Original 2D array:\n", array_2d)
print("Raveled array:", raveled_array)
print("Flattened array:", flattened_array)

Original 2D array:
 [[1 2 3]
 [4 5 6]]
Raveled array: [1 2 3 4 5 6]
Flattened array: [1 2 3 4 5 6]


Excercise

In [17]:
rows = 5
cols = 8

# Create the seating chart (seat numbers start at 1)
seating_chart = np.arange(1, rows * cols + 1).reshape(rows, cols)

print(seating_chart)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]]


Extract seats located in row 2 at columns 2 and 4.

In [19]:
specific_seats=seating_chart[1,[1,3]]
specific_seats

array([10, 12])

Extract all seats in row 3.

In [23]:
entire_row=seating_chart[2,:]
entire_row

array([17, 18, 19, 20, 21, 22, 23, 24])

Extract all seats in column 5.

In [22]:
entire_column=seating_chart[:,4]
entire_column

array([ 5, 13, 21, 29, 37])